version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-selenium
    container_name: selenium-hub
    restart: always
    ports:
      - "4444:4444"
  chrome:
    container_name: selenium-ahoy-chrome
    image: selenium/node-chrome-debug
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - 32771:5900
  ruby:
    image: zibby/ahoy-tester
    container_name: selenium-code
    restart: always
    depends_on:
      - selenium-hub
    volumes:
      - ./config.yml:/app/config.yml:ro
    command: bundle exec /app/main.rb /app/config.yml